### ISSUE TITLE
Move lint check to be in the prepare phase so that when it fails, tests are not run

### ISSUE THREAD

**Issue by brynjarorng** [island-is/island.is#10118]

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
