### ISSUE TITLE
Add a step in deployment pipeline to deploy and wait for search-indexer before deploying the whole thing

### ISSUE THREAD

**Issue by brynjarorng** [island-is/island.is#10117]
We need this because we want the search-indexer to have completed migrations before deploying the rest of the islandis chart.

If the whole chart is deployed and the search-indexer hasn't made the new index then we might run into situations where users see only some/no content for the duration of the migration.

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
