### ISSUE TITLE
search-indexer-service to use graphql in contentful sync to elastic

### ISSUE THREAD

**Issue by peturgq** [island-is/island.is#10125]
We are currently using the REST way to sync content to elastic, we should sync up with @island-is/stefna and ask them to use graphql instead, so we can make one request vs 100s

Look into patching the indexes instead of rebuilding them.
CC: @island-is/aranja-core

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
