### ISSUE TITLE
NX version upgrade

### ISSUE THREAD

**Issue by busla** [island-is/island.is#10162]
We are currently using NX v13 and should upgrade to v15.

This will improve our chances that React native builds will work with NX

- [x] #10131

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
