### ISSUE TITLE
Kodiak merge issues

### ISSUE THREAD

**Issue by brynjarorng** [island-is/island.is#10203]
Behaves strangely by merging main multiple times into the branch but never merging the PR causing a buildup of stuck PRs that never get resolved. These PRs often have a failing test which means that a merge should not be queued. https://github.com/island-is/island.is/pull/10176

![Image](https://user-images.githubusercontent.com/1974615/221402404-ccb4b454-3729-4d90-8255-11535c847fc9.png)

![Image](https://user-images.githubusercontent.com/1974615/221402433-7c709881-edf8-4347-998a-3de23599c7ba.png)

**Comment by brynjarorng** [comment]
This is still an issue. Test timed out here, possibly due to needing to wait for workers which then got it killed https://github.com/island-is/island.is/actions/runs/4342919510/jobs/7584404480

**Comment by brynjarorng** [comment]
Happened again here https://github.com/island-is/island.is/pull/10573

**Comment by peturgq** [comment]
Look into merge queues from Github as a replacement.
