### ISSUE TITLE
Feature Deployments: Allow adding services to deploy with feature-deployment

### ISSUE THREAD

**Issue by peturgq** [island-is/island.is#10317]
Allow devs to add services to be deployed with their feature deployment through something like github slash commands

e.g 
/add-service (Adds to affected list) and generates a new build/deployment

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
