### ISSUE TITLE
PR fails when upstream branch is not main

### ISSUE THREAD

**Issue by busla** [island-is/island.is#10360]
```bash
++ LAST_GOOD_BUILD='Full rebuild needed'
Stickman done
++ echo 'Stickman done'
+++ echo 'Full rebuild needed'
+++ jq -r .sha
parse error: Invalid numeric literal at line 1, column 5
++ LAST_GOOD_BUILD_SHA=
Error: Process completed with exit code 4.
```

https://github.com/island-is/island.is/actions/runs/4355649402/jobs/7612553642

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
