### ISSUE TITLE
Update onboarding & DevOps documentation

### ISSUE THREAD

**Issue by AndesKrrrrrrrrrrr** [island-is/island.is#10395]
Needs to include:
- Recent merge-strategy changes
- Shared git  hooks
- CI autocommit & the need for pull

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
