### ISSUE TITLE
test shell scripts with ShellSpec

### ISSUE THREAD

**Issue by busla** [island-is/island.is#10419]
When we are creating/modifying shell scripts, particularly for pipelines, we should be running tests on them with ShellSpec (or another framework).

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
