### ISSUE TITLE
licenses of npm dependencies

### ISSUE THREAD

**Issue by nitschSB** [island-is/island.is#10421]
Hello,

we are using nx as well and currently struggling to publish the license information of the 3rd party libraries correctly.

I became aware of this repo through https://github.com/nrwl/nx/discussions/5483#discussioncomment-5108480 . 

I used the developer tools to search all web-sources of https://island.is/ for keywords "licence" "license" and "MIT" but got no useful results.

How do you respect 3rd party library licenses on https://island.is/?

Lots of `project.json`s in your repository contain `"extractLicenses": true,`. This leads to the generation of `3rdpartylicenses.txt` files but where do you link them and where do you publish them? Do you think that publication is enough to respect the license terms?

Cheers,
Mario

PS: I like this article about the topic https://medium.com/@vovabilonenko/licenses-of-npm-dependencies-bacaa00c8c65

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
