### ISSUE TITLE
NX Distributed Cache

### ISSUE THREAD

**Issue by peturgq** [island-is/island.is#10473]
Looks like a free, pretty painless way to drastically increase our CI times.
Looks like NX is very generous to the OSS community and we can apply for free enterprise https://nx.app/pricing

https://nx.dev/core-features/share-your-cache
https://dev.to/nrwl/more-time-saved-for-free-with-nx-cloud-4a2j

**Comment by busla** [comment]
being implemented here, closing
https://github.com/island-is/island.is/pull/11900
