### ISSUE TITLE
helm-values-validation failing, infra unknown dir #10654

### ISSUE THREAD

**Issue by busla** [island-is/island.is#10655]
Just to let you know, a recent commit to main seems to have failed a `helm-values-validation` pipeline run due to it not finding a directory.

<https://github.com/island-is/island.is/actions/runs/4531353759/jobs/7981396222>
<https://github.com/island-is/island.is/commit/8f7567104daade985dbe1a069abac58a60da4d58>

[Slack Message](https://islandis.slack.com/archives/C019LNRM6LE/p1679914083126599?thread_ts=1679914083.126599&cid=C019LNRM6LE)

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
