### ISSUE TITLE
Fix pre-release feature deployments always using mocks

### ISSUE THREAD

**Issue by brynjarorng** [island-is/island.is#10751]
Pre-release feature deployments currently use mountebank to mock responses. This in itself is good but currently our mocked responses are out of date and incorrect. We need to update the response objects and create a toggle somewhere in the DSL to turn this off. We also need a generic Readme file around this kind of mocking since it does not exist

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
