### ISSUE TITLE
create s3 bucket for e2e test files

### ISSUE THREAD

**Issue by busla** [island-is/island.is#10862]
Some e2e tests need files for testing file uploads.

One option is to include them in the monorepo but that doesn't scale well.

Another option would be to create a dedicated s3 bucket that the test script would download.

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
