### ISSUE TITLE
failed build run on prod regardless of PR success

### ISSUE THREAD

**Issue by busla** [island-is/island.is#10883]
Since we run builds with dev config on PRs we can not guarantee the same results on merge using prod config.

PR run success:
https://github.com/island-is/island.is/actions/runs/4574518541

Merge run failure:
https://github.com/island-is/island.is/actions/runs/4574623677/jobs/8076661060

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
