### ISSUE TITLE
Start using GITHUB_RUN_ID in our docker tags

### ISSUE THREAD

**Issue by peturgq** [island-is/island.is#10908]
So we end up with unique images when we hit the `re-run build` button.

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
