### ISSUE TITLE
Spinnaker failed feature-deploy on branch name regex

### ISSUE THREAD

**Issue by busla** [island-is/island.is#10913]
> Exception ( Monitor Deploy )
> 
>  Deploy failed: The Job "generate-values-1682420028851" is invalid: metadata.labels: Invalid value: "10903-allow-declaring-postgres-extensions-": a valid label must be an empty string or consist of alphanumeric characters, '-', '' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue', or 'my_value', or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9.]*)?[A-Za-z0-9])?')

https://github.com/island-is/island.is/pull/10904

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
