### ISSUE TITLE
auth-admin-web image disappeared

### ISSUE THREAD

**Issue by busla** [island-is/island.is#10926]
## Missing image

`imagePullBackoff` on `821090935708.dkr.ecr.eu-west-1.amazonaws.com/auth-admin-web:release-21-3-0_95b38df_61545`

was retagged originally, before the ecr lifecycle cleanup incident.

https://github.com/island-is/island.is/actions/runs/4610066246/jobs/8148153899

## Latest image

Rebuilt and pushed again at `21:45` when we triggered a full build the night of the incident
https://github.com/island-is/island.is/actions/runs/4737103823/jobs/8409557741 with the tag `821090935708.dkr.ecr.eu-west-1.amazonaws.com/auth-admin-web:release-21-3-0_1463c57_62305`

Should have been part of the deployment

**Comment by busla** [comment]
Looks like the lifecycle policies managed to grab this particular image 5 hours later. We disabled the lifecycle policies the day after.

This is unconfirmed since we can't see the exact images that were removed.

```
2023-04-19T03:53:22.000Z | PolicyExecutionEvent | 2 images affected
```

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
