### ISSUE TITLE
Fix Codecov branch targets, looks like currently main is the only target

### ISSUE THREAD

**Issue by peturgq** [island-is/island.is#10979]
Codecov seems to be reporting 0% changes.
https://github.com/island-is/island.is/pull/10929

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
