### ISSUE TITLE
Add a blocking step in the CI for branch name length limits

### ISSUE THREAD

**Issue by brynjarorng** [island-is/island.is#11103]
We are currently only using 0-45 characters in a branch name for feture image tags. A job that blocks the PR from running while these conditions are not met would make sure this issue never happens again in other places in the CI. See issue #11101

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
