### ISSUE TITLE
Flaky github ci workflows

### ISSUE THREAD

**Issue by brynjarorng** [island-is/island.is#11153]
We are seeing some workflows failing first time and needing a re-run quite frequently. This is sometimes due to github showing a screen with an X stating something like `Failed to run` and other times something such as:

```
Run yarn install --immutable
OCI runtime exec failed: exec failed: unable to start container process: chdir to cwd ("/__w/island.is/island.is/infra") set in config.json failed: no such file or directory: unknown
Error: Process completed with exit code 126.
```

https://github.com/island-is/island.is/actions/runs/4978273846/jobs/8908359117

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
