### ISSUE TITLE
Fix feature deployments ids url

### ISSUE THREAD

**Issue by brynjarorng** [island-is/island.is#11156]
The ids url is sometimes set to the prod url in feature deployments. I have a hunch it is related to a draft pr (then it's prod) but in non-draft PRs it works correctly

**Comment by peturgq** [comment]
This is due to application-system-form not being deployed along side the feature deployment, we need to find out why the injected HTML used is     
```<script id="__SI_ENVIRONMENT__" type="application/json">{"SI_PUBLIC_CONFIGCAT_SDK_KEY":"xxxxxxx","SI_PUBLIC_ENVIRONMENT":"prod","SI_PUBLIC_DD_RUM_CLIENT_TOKEN":"xxx","SI_PUBLIC_DD_RUM_APPLICATION_ID":"665a387d-16c4-4c86-88c8-e059d8120021","APP_VERSION":"release-22-2-0_42d902c_64616","SI_PUBLIC_IDENTITY_SERVER_ISSUER_URL":"https://innskra.island.is","SI_PUBLIC_GRAPHQL_PATH":""}</script>```

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
