### ISSUE TITLE
Groundwork for NX cloud

### ISSUE THREAD

**Issue by peturgq** [island-is/island.is#11220]
Attempt to use NX Cloud to improve CI performance and remove the need for compressing and storing CI build artifacts in S3.

Suggestions
- Create a workflow behind a feature flag, by setting `nx-cloud` label on a PR
- Use NX to build affected apps in a single runner and take advantage of [NX parallel builds](https://nx.dev/concepts/task-pipeline-configuration)
- To provision a runner that fits the size of the jobs, it would make sense to generate a list of jobs in a prepare stage with `nx print-affected` and count the number of jobs to determine the size of the runner that should be provisioned for the `build` job.

As an optimization feature after the above has been implemented, [NX distributed execution](https://nx.dev/core-features/distribute-task-execution) could be setup to improve the CI performance even more.

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
