### ISSUE TITLE
Generate GitHub Actions Annotation from Docker tag (and maybe other) to make the tag version more accessible

### ISSUE THREAD

**Issue by pshomov** [island-is/island.is#1131]
Suggested by @stefanhar

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
