### ISSUE TITLE
Cleanup parameters in parameter store

### ISSUE THREAD

**Issue by brynjarorng** [island-is/island.is#11465]
We are hitting the ratelimit to get parameters from parameter store. One solution is to remove unnecessary and unused parameters.

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
