### ISSUE TITLE
Implement `nx generate` templates

### ISSUE THREAD

**Issue by AndesKrrrrrrrrrrr** [island-is/island.is#11494]
See the `/tools` directory and [NX generate documentation](https://nx.dev/packages/nx/documents/generate)

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
