### ISSUE TITLE
Add poddisruptionbudget to DSL to reduce possible downtimes

### ISSUE THREAD

**Issue by peturgq** [island-is/island.is#11504]
We're seeing instances where applications have 0 pods available, this shouldn't be possible unless we really mean to.

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
