### ISSUE TITLE
Tackle issue with rate-limiting by changing patterns in workflows

### ISSUE THREAD

**Issue by peturgq** [island-is/island.is#11544]
This rate-limit issue with GH is causing annoyances for developers that we can be without, we should be able to easily change some of our workflows so they call the GH API less, we should do less paralellism in the builds and consolidate related steps into single steps

**Comment by peturgq** [comment]
NX cloud implementation and consolidation of steps will decrease this issue.
We're also going to run tests only when automerge label is applied.

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
