### ISSUE TITLE
Prepare judicial-system for deployment to Prod

### ISSUE THREAD

**Issue by pshomov** [island-is/island.is#1169]
The following is needed:

- [x] A prod database

- [x] /k8s/judicial-system/AUTH_JWT_SECRET - can be set to any secret string
- [x] /k8s/judicial-system/DB_PASSWORD - production db password provided by Andes
- [x] /k8s/judicial-system/NOVA_PASSWORD - can be copied from /k8s/gjafakort/NOVA_PASSWORD on prod - we are sharing the sms gateway
- [x] /k8s/judicial-system/JUDGE_MOBILE_NUMBER - 8999291
- [x] /k8s/judicial-system/DOKOBIT_ACCESS_TOKEN - Dokobit api secret provided by Kolibri - má afrita frá dev til að byrja með
- [x] /k8s/judicial-system/USER_SEED - user seeding provided by Kolibri - má afrita frá dev til að byrja með
- [x] /k8s/judicial-system/EMAIL_FROM - island@island.is
- [x] /k8s/judicial-system/EMAIL_FROM_NAME - ??? island.is ???
- [x] /k8s/judicial-system/EMAIL_REPLY_TO - no-reply@island.is
- [x] /k8s/judicial-system/EMAIL_REPLY_TO_NAME - ??? tómur strengur ???

- [x] An AWS service role with permission to send email via SES

- [x] Helm definitions https://github.com/island-is/helm/pull/78

**Comment by pshomov** [comment]
Requested by @gudjong

**Comment by gudjong** [comment]
To begin with it would be good to get a database on production.

**Comment by gudjong** [comment]
The following parameters are needed in AWS:

/k8s/judicial-system/AUTH_JWT_SECRET - can be set to **any secret string**

/k8s/judicial-system/DB_PASSWORD - production db password **provided by Andes**

/k8s/judicial-system/NOVA_PASSWORD - can be **copied from /k8s/gjafakort/NOVA_PASSWORD on prod** - we are sharing the sms gateway

/k8s/judicial-system/JUDGE_MOBILE_NUMBER - on-call mobile phone shared by judges **provided by Kolibri**

/k8s/judicial-system/DOKOBIT_ACCESS_TOKEN - Dokobit api **secret provided by Kolibri**

/k8s/judicial-system/USER_SEED - user seeding **provided by Kolibri**

**Comment by gudjong** [comment]
Dómsmálaráðuneytið wants to host the judicial system undir island.is/rettarvorslugatt

Is this possible?

**Comment by gudjong** [comment]
We will also need a service role that can send email via SES

**Comment by gudjong** [comment]
Allt komið.
