### ISSUE TITLE
Make sure security headers are in place for websites.

### ISSUE THREAD

**Issue by AndriMar** [island-is/island.is#1257]
Here is an example.
https://observatory.mozilla.org/analyze/vidspyrna.island.is
We see three solutions.
1. Here is an lambda edge solution.
https://aws.amazon.com/blogs/networking-and-content-delivery/adding-http-security-headers-using-lambdaedge-and-amazon-cloudfront/
2. Here is an ingress solution.
https://kubernetes.github.io/ingress-nginx/examples/customization/custom-headers/
3. Do this in the applications

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
