### ISSUE TITLE
Kennitala package updated to v2.0.0-beta.3

### ISSUE THREAD

**Issue by HermannBjorgvin** [island-is/island.is#12819]
Wanted to check to see if there's any feedback on the latest release of this package before it goes from beta to v2.0.0

https://www.npmjs.com/package/kennitala

Major changes: stricter type definitions, stricter validation, optional support for the thjodskra testing dataset.

The general API is 90% the same as before.

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
