### ISSUE TITLE
Remove sass support

### ISSUE THREAD

**Issue by darrikonn** [island-is/island.is#1315]
There are still some Sass files in our codebase, as well as `node-sass` dependency.

These sass files are located in:
```
apps/judicial-system/web/src/styles.scss
apps/application-system/form/src/styles.scss
```
^ might be autogenerated by `nx`. Not sure if this is used?

**Comment by darrikonn** [comment]
@arnifreyrs assigning you since the `application-system` file is from you.

**Comment by darrikonn** [comment]
@gudjong ^ same

**Comment by gudjong** [comment]
@oddsson ^ can you look at this?

**Comment by oddsson** [comment]
The reason we're using scss in the judicial-system project is for @font-face declarations. It's currently not possible to do this with Treat yet (source: https://github.com/seek-oss/treat/issues/93). NextJS apps have a way of doing this but that does not apply to plain React apps. @jeremybarbet suggested we'd have a root level .css file that projects import for this instead, that just hasn't been implemented. I'll put it on my backlog and fix it this week.
