### ISSUE TITLE
[island.is] User input sanitization in the search engine

### ISSUE THREAD

**Issue by helgim** [island-is/island.is#1383]
```code: &#39;ERR_INVALID_CHAR&#39;
at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17) {
    at parserOnIncoming (_http_server.js:784:12)
    at Server.emit (events.js:310:20)
    at Server.handleRequest (/webapp/node_modules/next/dist/next-server/server/next-server.js:17:112)
    at Server.run (/webapp/node_modules/next/dist/next-server/server/next-server.js:46:674)
    at Router.execute (/webapp/node_modules/next/dist/next-server/server/router.js:23:83)
    at Object.fn (/webapp/node_modules/next/dist/next-server/server/next-server.js:33:1152)
    at ServerResponse.setHeader (_http_outgoing.js:529:3)
    TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Location"]
    }
```
The service serving /en/search crashes(due to an unhandled exception) when a specially crafted request is made.
Example: https://island.is/en/search/?q=%90

**Comment by stefanhar** [comment]
There seems to be an open issue with next js related to this:
https://github.com/vercel/next.js/issues/17907

> User input for this functionality needs to be sanitized properly.
User input seems to be url encoded "%90" => "%2590"
Can you provide an example to help us better understand the issue?

**Comment by helgim** [comment]
An example of this would be sending a request in the manner I detailed in the issue.

```
$ http https://island.is/en/search/\?q\=%90
HTTP/1.1 500 Internal Server Error
Connection: keep-alive
Date: Fri, 16 Oct 2020 14:07:08 GMT
Server: nginx/1.17.8
Strict-Transport-Security: max-age=15724800; includeSubDomains
Transfer-Encoding: chunked
Via: 1.1 51a5a952c28afbcc082d59f6a902bb36.cloudfront.net (CloudFront)
X-Amz-Cf-Id: qmi32nbjxcp7sJF2u-7QE_HdRou-0jWDXhJsL1k96nPkb57-Ifp1Zg==
X-Amz-Cf-Pop: LHR62-C5
X-Cache: Error from cloudfront

Internal Server Error
```

A request from a user that sends a request that causes the issue, should not result in the service "crashing"[unhandled exception.]

The request crafted by the User Interface seems to be encoded beforehand so the problem is not in the UI but in the service receiving what the UI crafts.   We are only aware of this because of some spam bots that send these types of requests directly to /en/search/.

**Comment by eirikurn** [comment]
This error is in library code, not our code. The only ways to fix this error are:

* Try and "fix" these URLs in nginx.
* Set up a NextJS custom server and try to "fix" these URLs there.
* Set up patch-package in our repo and patch the NextJS fix ourselves.
* Wait until NextJS merges and releases the fix.

#2 is a bit tricky. I'd lean toward #4 myself, but #3 if this is unbearable in ops.

**Comment by helgim** [comment]
A fix has been applied in the library, according to the issue you linked @stefanhar.

Could you possibly get around to trying it out sometime soon?

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
