### ISSUE TITLE
Check in all pullrequests that ECR repository exists for all docker targets

### ISSUE THREAD

**Issue by sindrig** [island-is/island.is#1448]
We don&#39;t want to end up where we build+test okay, build the image okay, but can&#39;t push it because the repo doesn&#39;t exist. in that case we don&#39;t want to allow merging.

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
