### ISSUE TITLE
Way to bypass postinstall

### ISSUE THREAD

**Issue by saevarma** [island-is/island.is#1475]
Not sure if this has been raised as an issue before but I'm wondering if we could have an option to bypass the postinstall script.
The `/scripts/postinstall.js` script takes some time to execute and it executes even for `yarn add`.

**My use case**
I had recently executed `yarn schemas` which is essentially the same, so all auto generated files were up-to-date.
Then I needed to add a package to package.json and had to wait for the postinstall to finish again, a run that was not needed.

**Comment by eirikurn** [comment]
Good question. There is a CI variable that skips it. I usually ctrl-c the process when the `yarn` part is done, but maybe that's not common knowledge.

OTOH it is handy when pulling from main to update both dependencies and schemas with one command.

**Comment by saevarma** [comment]
> Good question. There is a CI variable that skips it. I usually ctrl-c the process when the `yarn` part is done, but maybe that's not common knowledge.
> 
> OTOH it is handy when pulling from main to update both dependencies and schemas with one command.

Yes, I should have thought of just ctrl-c
