### ISSUE TITLE
Feature request: Add WebAuthn standard for login

### ISSUE THREAD

**Issue by Gunni** [island-is/island.is#15321]
This is a direct continuation of https://github.com/island-is/island.is/issues/5190

- [Dæmi um að fólk tapi tugum milljóna](https://www.mbl.is/frettir/innlent/2023/01/27/daemi_um_ad_folk_tapi_tugum_milljona/)
- [Hægt að misnota rafræn skilríki með „einbeittum brotavilja“](https://www.visir.is/g/20151471619d/haegt-ad-misnota-rafraen-skilriki-med-einbeittum-brotavilja-)
- [Mis­notuðu raf­ræn skil­ríki og tæmdu tugi milljóna af reikningum eldri borgara](https://www.visir.is/g/20222236713d/mis-notudu-raf-raen-skil-riki-og-taemdu-tugi-milljona-af-reikningum-eldri-borgara)
- [Svikarar á ferli sem aldrei fyrr](https://www.mbl.is/frettir/burdargrein/2024/04/19/svikarar_a_ferli_sem_aldrei_fyrr/)
- [Svindlarar reyna að komast yfir rafræn skilríki](https://www.mbl.is/frettir/burdargrein/2023/03/17/svindlarar_reyna_ad_komast_yfir_rafraen_skilriki/)
- [Svíkja milljónir af granda­lausum Ís­lendingum í nafni Auð­kennis](https://www.visir.is/g/20242586858d/svikja-milljonir-af-grandvaralausum-islendingum-i-nafni-audkennis)
- [Vara við nýrri tegund af netsvikum](https://www.mbl.is/frettir/burdargrein/2023/10/05/vara_vid_nyrri_tegund_af_netsvikum/)

PDF: [FIDO Alliance White Paper: Using FIDO with eIDAS Services](https://fidoalliance.org/wp-content/uploads/2020/04/FIDO-deploying-FIDO2-eIDAS-QTSPs-eID-schemes-white-paper.pdf)

> # Conclusions
> To summarize, FIDO2 provides an easy-to-use and secured alternative to other potentially phishable solutions.
>  The FIDO2 standard is suitable as the authentication mechanism for substantial or high assurance levels for both eID schemes and for
authentication to a remote signing QTSP, as defined in the eIDAS regulation

[Austrian government adds YubiKeys to its electronic ID system](https://www.yubico.com/blog/austrian-government-adds-yubikey-support-to-its-national-electronic-identification-system/).

**Comment by eirikurn** [comment]
The Digital Iceland project management team currently do not use this issue tracker in any way. I suggest these avenues:

- Feature requests like this belong in the [Óskalisti þjóðarinnar](https://island.is/oskalisti-thjodarinnar) (I'd be more then happy to upvote this there).
- Issues or bug reports are best submitted through [Ísland.is support](https://island.is/adstod).
