### ISSUE TITLE
Cant pay for road tax at samgongustofa

### ISSUE THREAD

**Issue by judyfong** [island-is/island.is#16097]
With one 1 kr fee one is restricted from transfering a car over to the new owner
Ökutækiskipting. But thats weird. Cant the buyer just pay the fee?

**Comment by jonarnarbriem** [comment]
Hi @judyfong, the transport authority (Samgöngustofa) requires that all debts and fees belonging to the vehicle be paid before the ownership can be transferred. island.is just implements the policies of the institution it works for so if you have questions or suggestions I suggest you contact Samgöngustofa.
