### ISSUE TITLE
Kennitala@V2.0.2 update. Includes stricter validation and ES modules.

### ISSUE THREAD

**Issue by HermannBjorgvin** [island-is/island.is#16838]
I see you are still using the beta version of V2

I made some changes to modernize the library that include refactoring into TypeScript as well as supporting ES modules.

Can open a pull request with the update as well.

https://github.com/HermannBjorgvin/Kennitala/

**Comment by eirikurn** [comment]
Thanks for the suggestion. Moving to #16848
