### ISSUE TITLE
Document if resource apis should be prefixed with users collection or read from access token

### ISSUE THREAD

**Issue by saevarma** [island-is/island.is#2008]
Add documentation to the API Design Guide if a resource api should wrap the resource under a user collection:
```
/v1/users/:nationalId/documents
```
or if this user information should be availble from the access token, then document how resource api should read from the access token.

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
