### ISSUE TITLE
Downstream island.is accessbility guidance and tools

### ISSUE THREAD

**Issue by koddsson** [island-is/island.is#2009]
Web Accessability can be hard to achieve for institutions and companies due to time and/or monitory constraints. This is pretty detrimental to people who rely on assistive technology to navigate the web.

Digital Iceland has a mandate to make [all websites and government services accessible to all users](https://docs.devland.is/handbook/technical-overview/technical-direction#accessibility). This is terrific news and it&#39;s great to hear that the team are taking accessibility seriously and committing to go through automatic and manual accessibility audits.

With the accessibility expertise that will be built up through these audits, it seems to me that the team has a unique opportunity to open source its findings and tools, much how the [Government Digital Services (GDS) design system and frontend](https://design-system.service.gov.uk/accessibility/) does.

By down-streaming guidance & tools that other institutions and companies can use we can influence the Icelandic web ecosystem to become more accessible which will benefit _everyone_ that utilizes these services. 

>[Web accessibility also benefits people without disabilities, for example: people using mobile phones, smart watches, smart TVs, and other devices with small screens, different input modes, etc., older people with changing abilities due to ageing, people with “temporary disabilities” such as a broken arm or lost glasses, people with “situational limitations” such as in bright sunlight or in an environment where they cannot listen to audio, people using a slow Internet connection, or who have limited or expensive bandwidth](https://www.w3.org/WAI/fundamentals/accessibility-intro/#what)

I&#39;m not sure if this issue is the best medium to start this conversation but I wanted to just throw the idea of building up a guidance framework to all of you and see if this is something you are already thinking of or working on.

cc/ @axelg12

**Comment by eirikurn** [comment]
@island-is/stefna has been working on guidance internally. @ingolfurs is this something we can release somewhere, e.g. in the [handbook](https://docs.devland.is/handbook/)?

**Comment by axelg12** [comment]
Is there any about on this @eirikurn? I would love to contribute if any help is needed or if the guidance is ready to put it out publically.

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
