### ISSUE TITLE
Switch to stricter TypeScript config

### ISSUE THREAD

**Issue by eirikurn** [island-is/island.is#253]
The default TypeScript config from NX does not have any strict flags set, eg it allows implicit any. This makes it easy to forget to add type definitions to expressions and declarations and end up with unsafe untyped code.

It&#39;s an easy change in tsconfig.json, however, we already have a lot of code this will break.

To start this migration we should turn off strict in the root tsconfig. For projects that have a significant number of errors with this flag set, we can unset it in the project-specific tsconfig. Later, someone (optimally from the project team) has time to fix these type issues and re-enable strict mode.

**Comment by dabbeg** [comment]
So this is the current status of the strict setup even though me and @arnifreyrs took removed a lot of errors:
```
Errors Project
378 libs/api/domains/cms
378 apps/web
179 apps/judicial-system/api
174 apps/adgerdir
167 apps/air-discount-scheme/web
143 apps/gjafakort/web
111 apps/gjafakort/api
69  libs/island-ui/contentful
66  apps/air-discount-scheme/api
65  apps/judicial-system/web
54  libs/api/domains/content-search
41  apps/skilavottord/web
32  apps/application-system/api
29  libs/api/domains/application
28  apps/services/search-indexer
27  libs/api/domains/documents
18  libs/api/content-search
18  apps/gjafakort/application
11  libs/contentful-importer
10  apps/reference-next-app
10  apps/gjafakort/queue-listener
7   apps/skilavottord/ws
7   apps/reference-backend
6   libs/message-queue
5   libs/dokobit-signing
4   libs/infra-express-server
3   libs/island-ui/core
3   libs/elastic-indexing
3   apps/application-system/form
2   libs/service-portal/graphql
2   libs/service-portal/family
2   libs/api/domains/translations
1   libs/service-portal/documents
1   apps/api
```

Can we delegate fixing these type errors and removing `"strict": false` out of tsconfig.json to the codeowners? @eirikurn

Fixing the libs should be the highest priority because new projects with strict enabled cannot use a lib that has ts errors. Even though you explicitly disable strict in the lib.

**Comment by dabbeg** [comment]
If we split this up by CODEOWNERS we have something like:

```
kosmos-kaos
174 apps/adgerdir

kosmos-kaos og aranja
378 libs/api/domains/cms
378 apps/web

aranja
29  libs/api/domains/application
32  apps/application-system/api
3   apps/application-system/form

vice-versa
66  apps/air-discount-scheme/api
167 apps/air-discount-scheme/web
143 apps/gjafakort/web
111 apps/gjafakort/api
18  apps/gjafakort/application
10  apps/gjafakort/queue-listener

kolibri
5   libs/dokobit-signing
179 apps/judicial-system/api
65  apps/judicial-system/web


sendiradid
1   libs/service-portal/documents
2   libs/service-portal/graphql
2   libs/service-portal/family
27  libs/api/domains/documents

stefna
54  libs/api/domains/content-search
18  libs/api/content-search
28  apps/services/search-indexer

island-ui
69  libs/island-ui/contentful
3   libs/island-ui/core

devops
10  apps/reference-next-app
7   apps/reference-backend

???
11  libs/contentful-importer
3   libs/elastic-indexing
2   libs/api/domains/translations
41  apps/skilavottord/web
7   apps/skilavottord/ws
1   apps/api
```

**Comment by eirikurn** [comment]
The whole API project is now strict! 🎉

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
