### ISSUE TITLE
Create ADR for form library

### ISSUE THREAD

**Issue by eirikurn** [island-is/island.is#255]
Currently, island-ui has many components which build on top of Formik. This was chosen by default, but its worth investigating other form libraries and creating an [ADR](https://github.com/island-is/handbook/blob/master/docs/adr/index.md) for it.

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
