### ISSUE TITLE
Translation system

### ISSUE THREAD

**Issue by eirikurn** [island-is/island.is#256]
For system strings we&#39;re using `rosetta` and in-repo translation resources. This will not scale very far.

* It should be easy to set up translated user interfaces.
* Apps may be client-side or have server-side rendering.
* We want to namespace translations and only fetch translations that are needed for each context.
* It should be easy to add a new string to be translated, while still supporting a namespace and a description that gives context to editors/translators.
* It should be possible to configure deflection and pluraility rules for different languages.
* Editors should be able to tweak the copy and translators should be able to submit translations without involving developers.

One proposal is to combine Contentful with i18next (or something home built). We should create an ADR for this.

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
