### ISSUE TITLE
Library for shared assets

### ISSUE THREAD

**Issue by eirikurn** [island-is/island.is#257]
Currently we have a few applications which are duplicating assets like favicons.

We should avoid duplicating assets. Instead we can create a shared library that contains these assets.

From there, they can be imported using `webpack`, or we can copy them to a public folder in the build step.

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
