### ISSUE TITLE
Paths with "-" result in internal server error status code 500

### ISSUE THREAD

**Issue by AndriMar** [island-is/island.is#2682]
Looks like paths with "-" are returning 500 error code.
This results in internal server error:
https://island.is/andes-foo/andes-bar
This is fine:
https://island.is/foo/bar

Although if the path exists then it&#39;s fine to have "-"
https://island.is/lifsvidburdur/ad-eignast-barn

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
