### ISSUE TITLE
AccessDeniedException when creating secret

### ISSUE THREAD

**Issue by fjandakornid** [island-is/island.is#2772]
Trying to create secret on AWS.

Steps:
- Open "Command line or programmatic access" link for island-is-shared.
- Copy the "Option 1: Set AWS environment variables" and paste into my terminal.
- paste "export AWS_REGION=eu-west-1" into the terminal
- run "yarn create-secret" and fill in the name and value. Click 'y' when promted and "Creating secret..." is displayed.

Error contained my user info so instead of pasting it here, it was sent to Jón Levy @ Andes by Slack PM.

**Comment by hrefnalind** [comment]
@sindrig can you provide me with ETA on this issue please ?
