### ISSUE TITLE
Kennitala v1.2.5 version release

### ISSUE THREAD

**Issue by HermannBjorgvin** [island-is/island.is#3041]
This version fixes the math behind age calculations, in some cases a person can be the wrong age a day before their birthday.

Version `1.2.5` fixes this with no breaking changes.

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
