### ISSUE TITLE
review monitoring of ui.devland.is

### ISSUE THREAD

**Issue by busla** [island-is/island.is#3120]
ui.devland.is is being monitored and is reporting 403 errors. Discuss if that might need some reevaluation.

See incident and note:
https://andes.pagerduty.com/incidents/PF2J7YF?utm_source=slack&utm_campaign=channel

**Comment by busla** [comment]
I excluded `ui` from the monitor.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
