### ISSUE TITLE
Publish Island UI to NPM

### ISSUE THREAD

**Issue by eirikurn** [island-is/island.is#3195]
We want to allow other repos to use Island UI.

We may need to refactor @island.is/island-ui/core to do this, and decide on some publish rhythm and versioning system.

- [x] Publish pre-release version.
- [x] Setup next example repo.
- [x] Setup CRA example repo.
- [x] Fix production build for CRA. 
- [x] Add payment flow example to CRA.
- [x] Add docs and disclaimers to island ui (not officially release yet, proceed with caution).
- [x] `ReferenceError: $RefreshSig$ is not defined`
- [ ] Use NX builder to handle package bundling
- [ ] Setup automatic release action
- [ ] Setup automatic changelog action

**Comment by jeremybarbet** [comment]
- The first alpha version of the Island UI is available on NPM [here](https://www.npmjs.com/package/@island.is/ui)
- A demo project for Next.js is available [here](https://github.com/island-is/island-ui-next-example)
- A demo project for Create React App is available [here](https://github.com/island-is/island-ui-cra-example)
- Pull request used to deploy the Island UI to NPM is [here](https://github.com/island-is/island.is/pull/3356)

The next step is to define a deployment pipeline and have a proper bundle for typescript files.

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
