### ISSUE TITLE
Create a new DB for Digital Iceland and move data from the old DB to the new SÍ DB

### ISSUE THREAD

**Issue by lindalyngmo** [island-is/island.is#3224]
Please create a new database for Stafrænt Ísland and move the official database of Icelandic names, hosted at Hugsmidan at the moment, over to SÍ´s new DB.

Detailed information:
We are moving the official database of Icelandic names over to SÍ.
The plan is to make the data in the new DB (hosted at SÍ) available through the central API.
We also plan to create a small admin app for SÍ to interface with this database.

Screenshot of the table structure of the current DB:
![image](https://user-images.githubusercontent.com/66788031/110809261-a2928900-827c-11eb-9563-518a6e37e5f5.png)

- [ ] Tala við Lindu

**Comment by lindalyngmo** [comment]
Any news? :)

**Comment by pshomov** [comment]
It is next on the backlog I believe.

**Comment by pshomov** [comment]
@lindalyngmo Can we get a contact in Hugsmiðjan to help us with the access to the DB there?

**Comment by lindalyngmo** [comment]
Yes, her name is Ingibjörg Ólafsdóttir, ingibjorg@hugsmidjan.is ;) I can also connect you with each other if you want, just let me know

**Comment by pshomov** [comment]
[IcelandicName.zip](https://github.com/island-is/island.is/files/6211447/IcelandicName.zip)

**Comment by pshomov** [comment]
I suggest the work on this can start. The SQL dump we got from Hugsmiðjan can be used as a seed in the app due to the unique circumstances that this DB/table should never be updated besides approval from the naming committee. I suggest that all changes to the table should happen through a seed. Thoughts @lindalyngmo?
