### ISSUE TITLE
Build and deploy static assets to S3/CDN

### ISSUE THREAD

**Issue by eirikurn** [island-is/island.is#3316]
Currently, all of our apps only serve the current version of static assets in production. This can be dangerous in production, since our apps are SPA, and our users might continue browsing for some time after a new version has been deployed.

Cloudfront softens the blow, having some older files cached, but it can&#39;t be trusted. As we start deploying more rapidly, more and more users will encounter random issues with this.

It&#39;s better to serve all static files from a public S3 bucket, with Cloudfront in front of it, eg cdn.island.is. Then we can keep older files around for a while.

For optimal client-side caching for SPAs, it&#39;s best to have the same URLs for files (no subfolder per deploy). The tricky thing is how we clean up the bucket of files that are no longer needed. Ideally:

* Files are hosted flat: `https://cdn.island.is/service-portal/main.{sha}.js`
* We re-build and re-deploy all apps every once in a while (eg at least every month).
* We configure an S3 lifecycle rule that deletes old files (eg more than 3 months old).
* We make sure that every re-deploy touches or replaces existing files, to restart lifecycle timers.

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
