### ISSUE TITLE
air-discount-scheme-backend: Implement readiness checks for Þjóðskrá API endpoint

### ISSUE THREAD

**Issue by helgim** [island-is/island.is#3374]
We are currently faced with an issue where the Þjóðskrá API endpoint used by air-discount-scheme-backend is down.  Currently this causes the service to crash and entering a CrashLoop State in Kubernetes after a while.

It would be good to incorporate a check for the service&#39;s Kubernetes Readiness endpoint, where it checks if Þjóðskrá is up.  If Þjóðskrá is OK, the endpoint should return 200OK - if the Þjóðskrá is down, the service should return the 500 status code, along with logging the cause for the failure.

(this depends on whether Þjóðskrá is a vital component for the air-discount-scheme-backend service.)

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
