### ISSUE TITLE
auth-admin-web and services-auth-admin-api need to set up on staging environment (and production later)

### ISSUE THREAD

**Issue by unnarb** [island-is/island.is#3396]
Is is possible to have the service layer internal and not open to the internet?

**Comment by pshomov** [comment]
We need bit more details. We should discuss this a bit more over a video session.

**Comment by valurefugl** [comment]
I would like to participate in discussions in a video session, can we do that tomorrow?

**Comment by hrefnalind** [comment]
@Andes Please have this as a high priority on your list.
