### ISSUE TITLE
Error when opening developer handbook

### ISSUE THREAD

**Issue by Hilmar68** [island-is/island.is#3422]
When trying to access the developer handbook on the url "https://docs.devland.is/handbook/technical-overview/x-road" i get error
 
This site can’t provide a secure connectiondocs.devland.is uses an unsupported protocol.
ERR_SSL_VERSION_OR_CIPHER_MISMATCH

**Comment by jeremybarbet** [comment]
The doc is now back online. All the documentations for X-ROAD is available here https://docs.devland.is/technical-overview/x-road
