### ISSUE TITLE
Redirect for /syslumenn

### ISSUE THREAD

**Issue by ingolfurs** [island-is/island.is#3519]
We need to create redirect for **island.is/syslumenn** to the page [island.is/stofnanir/syslumenn](https://island.is/stofnanir/syslumenn)

**Comment by ingolfurs** [comment]
@sindrig The redirect works on beta, but I still get 404 error on [island.is/syslumenn](http://island.is/syslumenn)

**Comment by sindrig** [comment]
@pshomov is aiming to apply this tonight

**Comment by ingolfurs** [comment]
[island.is/syslumenn](http://island.is/syslumenn) is now redirecting to island.devland.is/stofnanir/syslumenn
but was supposed to redirect to [island.is/stofnanir/syslumenn](https://island.is/stofnanir/syslumenn)

**Comment by sindrig** [comment]
```
sindri->~ (island-shared:e2e-dev) $ curl -XGET -I https://island.is/syslumenn
HTTP/2 301 
content-type: text/html
content-length: 134
location: https://island.is:443/stofnanir/syslumenn
server: awselb/2.0
date: Tue, 04 May 2021 11:53:38 GMT
x-cache: Hit from cloudfront
via: 1.1 39159a0d814f803c2a493023a4925c01.cloudfront.net (CloudFront)
x-amz-cf-pop: LHR3-C1
x-amz-cf-id: efdtN6oylO61neX0vk1r9C45bHw_Xe_7jZvwlFctoJ5giGU4NHD4tA==
age: 23
```
