### ISSUE TITLE
Redirect island.is/element og island.is/elementsofai

### ISSUE THREAD

**Issue by vigfusg** [island-is/island.is#3547]
Frá Vigdísi Jóhannsdóttur:
island.is/element og island.is/elementsofai
... inn á island.is/elemennt

**Comment by VigdisJohanns** [comment]
Virkar ekki enn, kemur 404 villa - ætti það að komast í lag við útgáfuna sem er á leiðinni út?

**Comment by VigdisJohanns** [comment]
ps. can you share the answer on when it's up and running to slack since I spend very little time in here :)
