### ISSUE TITLE
Enable consistend type imports eslint rule for the repo

### ISSUE THREAD

**Issue by sindrig** [island-is/island.is#4001]
There is this rule available for import types https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/consistent-type-imports.md I guess it would be nice to enable it for the whole repo

_Originally posted by @jeremybarbet in https://github.com/island-is/island.is/pull/3024#discussion_r641362056_

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
