### ISSUE TITLE
Fix jumping content when toggling font-weight

### ISSUE THREAD

**Issue by darrikonn** [island-is/island.is#4027]
![checkbox](https://user-images.githubusercontent.com/5694851/120308847-0d73bf00-c2c4-11eb-93b8-7695abb16b94.gif)

Could use `text-shadow` instead of changing the `font-weight` to prevent the content jump.

**Comment by barabrian** [comment]
I would recommend adding a transparent copy of the text in bold and position the visible text on top so the bolded text space is already calculated that would remove layout shifts
