### ISSUE TITLE
Enable auth apis to communicate with Þjóðskrá service in xroad

### ISSUE THREAD

**Issue by valurefugl** [island-is/island.is#4082]
Seems like we need to open for communication from the two following namespaces to the new Þjóðskrá service:

identity-server
identity-server-admin

**Comment by valurefugl** [comment]
Seems like all is working fine for service in identity-server-admin (services-auth-public-api). But in identity-server namespace (services-auth-api) we get this [error](https://app.datadoghq.eu/logs?cols=core_host%2Ccore_service&from_ts=1623222652125&index=%2A&live=true&messageDisplay=inline&query=service%3Aservices-auth-api&stream_sort=desc&to_ts=1623226252125&event=AQAAAXnvyri2Qp8U7gAAAABBWG52eXNpV0FBQlJjRHZzZXRHNm53QVA).

**Comment by valurefugl** [comment]
Turns out this was a bug in the IDS configuration, all good now on dev. Closing this.

**Comment by pshomov** [comment]
Need to re-open this since there is infrastructure to be deployed on prod that is not complete as of yet.
