### ISSUE TITLE
Add pre-commit/push hooks documentation to "Getting started" doc in monorepo for those that do want to have it setup

### ISSUE THREAD

**Issue by pshomov** [island-is/island.is#4088]

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
