### ISSUE TITLE
Feature flag service - comments

### ISSUE THREAD

**Issue by ivarconr** [island-is/island.is#4100]
Hi there 👋🏼 

the author and maintainer of Unleash here. I was just made aware of [0013-feature-flags.md](https://github.com/island-is/island.is/blob/main/handbook/technical-overview/adr/0013-feature-flags.md) Really love your open process 👍🏼  

For you evaluation of [Unleash](https://github.com/unleash) I have a few comments I would like to highlight:
- You are only evaluating our Open-Source edition and not the Enterprise offering, while you compare it against other commercial offerings. It would be good if you could highlight that in your summary of Unleash. 
- The [Unleash Enterprise](https://www.getunleash.io/plans) offering do have environment support and authorization. 
- We are very privacy concerned and do a lot of things to avid sharing end-user data with our service.  We believe so hard in this that we last week even open-sourced the [Unleash Proxy](https://docs.getunleash.io/sdks/unleash-proxy), so that you can use feature flags with single-page/native applications, without exposing end user data with the Unleash API itself. 
- Starting from Unleash v4 also the Open-Source comes with authentication and authorization out of the box. 

When it comes to the UI part I totally agree that there are some improvements to be done. We are currently investing heavily in that area. We just rewrote the hole frontend using material-ui and plan to work closely with our users. 

**Would you be available for a feedback session, to help us understand how we can improve?** 
If yes, please reach out to ivar[at]getunleash.io

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
