### ISSUE TITLE
Cleanup judicial system secrets

### ISSUE THREAD

**Issue by gudjong** [island-is/island.is#4111]
The following secrets are no longer used and need to be deleted from staging and prod:

/k8s/judicial-system/COURT_MOBILE_NUMBERS
/k8s/judicial-system/COURT_USERNAME
/k8s/judicial-system/COURT_PASSWORD

Please note that there is a secret still being used called COURTS_MOBILE_NUMBERS that should absolutely not be deleted.

**Comment by sindrig** [comment]
`/k8s/judicial-system/COURT_USERNAME` not found. others deleted
