### ISSUE TITLE
`kennitala` module not really usable for eslint

### ISSUE THREAD

**Issue by maranomynet** [island-is/island.is#4501]
The `kennitala` module is way too aggressive in auto-ignoring obvious hints that a random string is not a kennitala.

```js
import * as kennitala from &#39;kennitala&#39;

const notAKennitala = &#39;rgba(204, 153, 0, 0,05)&#39;
kennitala.isValid(notAKennitala) // true   o_O
```

Its over-eager internal re-formatter even gives false positives on 9-digit strings:

```js
const alsoNotKennitala = &#39;101.304.339 kr&#39;
kennitala.isValid(alsoNotKennitala) // true   0_o
```

This means that the `local-rules/disallow-kennitalas` linter will false-positive on random strings.

Maybe not a huge issue, but it does beg the question whether a project of this size should maybe upgrade to a stricter, more reliable (and leaner?) kennitala module.

https://github.com/island-is/island.is/blob/b4d3b54f005957ed0ec4ea78c4740d4daabe0cf5/eslint-local-rules.js#L16

**Comment by HermannBjorgvin** [comment]
V2 is on the way. Originally my thought was that formatting differences such as the dash separator vs no dash separator might be solved just by stripping non digit characters. But yes maybe it was too aggressive, I think I will fix this in the next version to only validate ID's that are also correctly formatted.

V2 is in beta now but should be published soon with support for the new temporary ID format as well.

Will keep you posted.

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
