### ISSUE TITLE
Add documentation for how go gain access to secrets and other env variables

### ISSUE THREAD

**Issue by arnifreyrs** [island-is/island.is#458]
Some environment variables should not be required during development, might depend on what project you are developing

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
