### ISSUE TITLE
application-system-form static assets routing issue

### ISSUE THREAD

**Issue by busla** [island-is/island.is#4581]
```bash
2021/07/23 15:21:37 [error] 52#52: *124486 open()
"/usr/share/nginx/html//frambod/polyfills.303df476708f95c783a3.esm.js" failed (2: No such file or directory),
client: 10.64.9.26,
server: localhost,
request: "GET /umsoknir/frambod/polyfills.303df476708f95c783a3.esm.js HTTP/1.1",
host: "island.is"
```

In terms of Nginx, the path fragments seem to be translated to the file lookup, should probably only be `/usr/share/nginx/html`

I can confirm that the file exists in the container: `/usr/share/nginx/html/polyfills.303df476708f95c783a3.esm.js`

**Comment by jeremybarbet** [comment]
Are you able to see from where this one comes from?

```
https://island.is/umsoknir/polyfills.303df476708f95c783a3.esm.js
```

that’s the one I get when accessing https://island.is/umsoknir/frambod

I’m wondering at which stage it adds the frambod  into the path

**Comment by busla** [comment]
I think I will close this for now since this occured during an issue we were having with one of the party registrations that has now been fixed. It has not occured since.

**Comment by busla** [comment]
Reopening this since we are seeing this in the logs again.

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
