### ISSUE TITLE
logger library for client side

### ISSUE THREAD

**Issue by jeremybarbet** [island-is/island.is#4598]
Many times I imported our logger library into a client-side code and it just crashed. The errors are so not intuitive that it wasn&#39;t easy to guess that it was coming from the logger library. But now I know.

I was checking on Winston and there is a "browser-console" transporter but didn&#39;t try it. It would be nice to be at least be able to import the logger from the same library but depending if on client or server-side to use a different function. If not Winston, maybe simply mirroring `logger.error` to `console.error`.

It would probably be interesting to have Sentry used for the client-side as well in addition 

Cf: 8 years old issue :D https://github.com/winstonjs/winston/issues/287

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
