### ISSUE TITLE
DNS breytingar - nytingaryfirlit og leyfi

### ISSUE THREAD

**Issue by vigfusg** [island-is/island.is#4813]
we need to remove the nytingaryfirlit.island.is and leyfi.island.is from our DNS .. cleanup.

**Comment by dabbeg** [comment]
Removed `nytingaryfirlit.island.is` and `leyfi.island.is` from our DNS.

In the process I saw these records that I suspect can also be cleaned up, can you confirm @vigfusg?
```
apinytingaryfirlit-t.island.is	     A
apinytingaryfirlit.island.is	     A
apinytingaryfirlittest.island.is     A
nytingaryfirlit-t.island.is	     A
```

**Comment by vigfusg** [comment]
I can confirm that these records can also be removed.

**Comment by dabbeg** [comment]
Removed
