### ISSUE TITLE
syslumenn.is - DNS to island.is

### ISSUE THREAD

**Issue by vigfusg** [island-is/island.is#5564]
island.is is now hosting syslumenn, i.e. island.is/syslumenn 

What to do:
a. syslumenn.is redirect to island.is/syslumenn
b. syslumenn.is moved to DNS of island.is

https://isnic.is/is/whois/search?query=syslumenn.is

Contact and needs to be in sync with: Bryndís Pétursdóttir bryndis.petursdottir@dmr.is

**Comment by vigfusg** [comment]
Ath, dig á syslumenn.is gefur MX og TXT sem þarf að finna út úr.

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
