### ISSUE TITLE
Add a Docker container type for serving static content -  React, etc.

### ISSUE THREAD

**Issue by pshomov** [island-is/island.is#614]
We plan on using Nginx to serve the content

**Comment by eirikurn** [comment]
Some things to bear in mind:

* For client-side routing we need to serve the same index.html for all paths (possible with both nginx and nodejs server).
* How do we use the same binary container and pass environment variables to static content (eg API_URL). These are usually built into static bundles, but it's probably worth investing in some way to get configuration at runtime. Either through some configuration service/endpoint or preferably injecting stuff directly into the index.html file at runtime (to save an extra request).

**Comment by eirikurn** [comment]
@pshomov are the points above addressed in #654 or helm somehow? Or should we create new issues for them?
