### ISSUE TITLE
Links in readme for third parties are broken

### ISSUE THREAD

**Issue by bergur** [island-is/island.is#6191]
https://github.com/island-is/island.is/blob/main/handbook/technical-overview/auth/third-party-manual/README.md

**Comment by eirikurn** [comment]
These links are to a repo that's currently private unfortunately. The new IDP is currently in a closed testing phase with a few integration partners.

We plan to update the docs before the new IDP gets a wider release later this year.

cc @hrefnalind

**Comment by Gunni** [comment]
> this year
o.O

**Comment by hrefnalind** [comment]
Technical documentation regarding IDS has been updated and is maintained here: https://docs.devland.is/technical-overview/auth You can for example find integration guidelines there.

**Comment by saevarma** [comment]
Closing this issue as the documentation has been updated and moved.
