### ISSUE TITLE
Add support for feature deployment of services using SQS

### ISSUE THREAD

**Issue by pshomov** [island-is/island.is#6373]
Currently feature deployment of SQS-using services and jobs interfere with one another and the one on Dev. We should fix this at three levels, some of the are optional:

- [x] #6403
- [x] #6393
- [x] #6722

**Comment by pshomov** [comment]
FYI @arnorhs @maggisk

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
