### ISSUE TITLE
Cognito cookie and interaction with Nextauth

### ISSUE THREAD

**Issue by JuliusGG** [island-is/island.is#6432]
When using dev and staging for Air-discount-scheme(possibly other projects) on initial load the path is not the same as predefined path of nextauth.

dev nextauth_url is `https://loftbru.dev01.devland.is`
staging nextauth_url is `https://loftbru.staging01.devland.is`

----------

The browser console error looks like this
`Access to manifest at &#39;https://auth.shared.devland.is/staging/oauth2/start?rd=https%3A%2F%2Floftbru.staging01.devland.is/site.webmanifest&#39; (redirected from &#39;https://loftbru.staging01.devland.is/site.webmanifest&#39;) from origin &#39;https://loftbru.staging01.devland.is&#39; has been blocked by CORS policy: No &#39;Access-Control-Allow-Origin&#39; header is present on the requested resource.
auth.shared.devland.is/staging/oauth2/start?rd=https%3A%2F%2Floftbru.staging01.devland.is/site.webmanifest:1 `

The network tab sends such a request:
`start?rd=https%3A%2F%2Floftbru.staging01.devland.is/site.webmanifest
set-cookie: _oauth2_staging_csrf=f0f2e4453b3d06f7b53377cbc2471711; Path=/; Domain=devland.is; Expires=Mon, 07 Feb 2022 12:58:36 GMT; HttpOnly; Secure; SameSite`

when exploring application tab  -> cookies I see the staging cookie is called `_oauth2_staging` not `_oauth2_staging_csrf` like in the network request shown above.

--------
To be clear - afaik everything is working correctly, only the initial load creates errors that (probably) does not impact anything.

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
