### ISSUE TITLE
Build process for mobile app

### ISSUE THREAD

**Issue by pshomov** [island-is/island.is#6447]
- [x] #6477
- [x] #6478
- [x] #8196
- [ ] CI process for iOS
- [ ] CI process for Android

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
