### ISSUE TITLE
Add tags to all images to help with ECR Lifecycle policies

### ISSUE THREAD

**Issue by Snojo** [island-is/island.is#6469]
We need to add tags to all images to help with lifecycle policies. 
The tag needs to be a prefix which we can configure the lifecycle policies on. 
Something like "release-" for all release images
"feature-" for feature branch images
"main-" for main branch builds
etc. 

When we have these in place, we can configure lifecycle policies to keep f.e. all release images forever, while only keeping feature images for 90 days.

**Comment by Snojo** [comment]
Add release-latest tag to keep forever

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
