### ISSUE TITLE
Look into CI tools for automatic Helm Chart Management

### ISSUE THREAD

**Issue by Snojo** [island-is/island.is#6683]
Check what options are available out there for automatic helmchart installations. 
Something like https://github.com/fluxcd/helm-controller ? 
or ArgoCD.

**Comment by Snojo** [comment]
We can also just do terraform or implement this into our CI Pipeline

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
