### ISSUE TITLE
Datadog Agent: Fix invalid syntax

### ISSUE THREAD

**Issue by pshomov** [island-is/island.is#6839]
https://app.datadoghq.eu/logs?query=status%3Aerror%20env%3Aprod%20service%3Aagent&cols=host%2Cservice&index=&messageDisplay=inline&stream_sort=desc&from_ts=1646818284442&to_ts=1646819184442&live=false

It's like 30-40% of all logs on prod right now...

**Comment by Snojo** [comment]
Old PR: https://github.com/island-is/island.is/pull/6482/files
