### ISSUE TITLE
Formatting checks everything

### ISSUE THREAD

**Issue by kristofer-lp8f** [island-is/island.is#6859]
From the CLI when run manually:
```shell
$ nx format:check --all

>  NX   WARNING  Running affected:* commands with --all can result in very slow builds.

  --all is not meant to be used for any sizable project or to be used in CI.
  
  Learn more about checking only what is affected: https://nx.dev/latest/angular/cli/affected#affected.
```

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
