### ISSUE TITLE
Give HotBot a Visual Status of Builds

### ISSUE THREAD

**Issue by Snojo** [island-is/island.is#7240]
Should be pretty easy by creating a second stage to finish up and using the chat.update api from slack 

https://api.slack.com/messaging/modifying#updating
https://api.slack.com/methods/chat.update#valid_message_types

Need to find a way to persist the message token used by the first stage. 

Also TODO: 

- [ ] Make sure names are always string when pulled from spinnaker. When it adds the ((anonymous)) tag it fucks up the syntax

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
