### ISSUE TITLE
Rework and Document the Revert Process for faulty releases

### ISSUE THREAD

**Issue by Snojo** [island-is/island.is#7293]
Create Revert Documentation for issues during release. 

1. Double check DB migrations
2. Have a functional DB Downgrade script: https://github.com/island-is/island.is/issues/7060

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
