### ISSUE TITLE
Reduce 200 spam marked as Error on all envs for Prometheus Adapter

### ISSUE THREAD

**Issue by Snojo** [island-is/island.is#7403]
https://app.datadoghq.eu/logs?query=env%3Aprod%20status%3A%28emergency%20OR%20error%29%20service%3Aprometheus-adapter&index=&from_ts=1652203322546&to_ts=1652376122546&live=true

**Comment by peturgq** [comment]
Deployed to dev, staging and prod:
https://github.com/island-is/infrastructure/pull/1238
