### ISSUE TITLE
Interference between Github Auth and innskraning.island.is callback

### ISSUE THREAD

**Issue by pshomov** [island-is/island.is#742]
The POST callback from innskraning.island.is becomes GET after Github interjects into the process.
Issue pointed out by @gudjong

**Comment by gudjong** [comment]
I made some tests for both http://judicial-system.dev01.devland.is/ and https://ads.dev01.devland.is/

In both cases the authentication succeeds on the second attempt if logged into GitHub. The first attempt returns:

{
statusCode: 404,
error: “Not Found”,
message: “Cannot GET /api/auth/callback”
}

**Comment by gudjong** [comment]
I then did some tests when not logged into Github.

Then I am always redirected to the Github login page. If I log into github I get the same 404 error as in the previous comment. If I then remain logged into Github I can successfully log in to the apps (ads and judicial-system).

Very strange behaviour, but must have some reasonable explanation :)

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
