### ISSUE TITLE
Test Case: A logged in user should have some message in their inbox

### ISSUE THREAD

**Issue by pshomov** [island-is/island.is#7575]
Visit `/minarsidur/postholf` as a user known to have messages in their inbox, verify inbox is non-empty

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
