### ISSUE TITLE
Test Case: Having selected English language at the front page, the service portal should be in English on login

### ISSUE THREAD

**Issue by pshomov** [island-is/island.is#7594]

**Comment by kristofer-lp8f** [comment]
Not clear this is the intended functionality. Need to verify whether language in service-portal is set by user-profile or front-page language.

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
