### ISSUE TITLE
Call for help 👉  Textarea component

### ISSUE THREAD

**Issue by oddsson** [island-is/island.is#764]
In our project we are using a textarea field that looks like this 👇

![Screenshot 2020-09-10 at 19 40 09](https://user-images.githubusercontent.com/3789875/92793786-394dbe00-f39e-11ea-8349-83f31c00d508.png)

What I need is to be able to choose if an input field should be rendered as a textarea or input via a prop when using the input component. I tried implementing this myself but was unable to get working due to typescript errors regarding the merging of refs in the Input component. Can anyone please help?

**Comment by eirikurn** [comment]
Is it worth creating this as a standalone component? It probably has some props and special style/JS logic that is not relevant for normal inputs (and vice verca?).
