### ISSUE TITLE
Chatbot test disruption fix

### ISSUE THREAD

**Issue by pshomov** [island-is/island.is#7781]
# What
Tests on pages that contain the Chatbot are failing.

# Expected Behavior
Input should keep focus when the chatbot is rendered during tests.

# Current Behavior
* Inputs loose focus during tests while typing when the Chatbot is rendered in the DOM.
* Does not happen outside of the test environment.
* Looks like a complete DOM re-render when the Chatbot is introduced, the page flickers.

**Comment by kristofer-lp8f** [comment]
Workaround for now: https://github.com/island-is/island.is/pull/7792
