### ISSUE TITLE
SQS troubleshooting with Kolibri team

### ISSUE THREAD

**Issue by pshomov** [island-is/island.is#7812]

**Comment by Snojo** [comment]
`{"date":"Mon Jul 04 2022 09:54:08 GMT+0000 (Coordinated Universal Time)","error":{"$fault":"client","$metadata":{"attempts":1,"httpStatusCode":403,"requestId":"952d2036-a9d0-50bf-b578-7b0a12d0bcbe","totalRetryDelay":0},"Code":"AccessDenied","Detail":"","Type":"Sender","name":"AccessDenied"},"exception":true,"level":"error","message":"unhandledRejection: Access to the resource https://sqs.eu-west-1.amazonaws.com/ is denied.\nAccessDenied: Access to the resource https://sqs.eu-west-1.amazonaws.com/ is denied.\n    at deserializeAws_queryCreateQueueCommandError (/webapp/main.js:554829:43)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async /webapp/main.js:550162:22\n    at async /webapp/main.js:563132:22\n    at async StandardRetryStrategy.retry (/webapp/main.js:560695:42)\n    at async /webapp/main.js:559369:24","os":{"loadavg":[2.98,1.66,1.43],"uptime":2926300.02},"process":{"argv":["/usr/local/bin/node","/webapp/main.js"],"cwd":"/webapp","execPath":"/usr/local/bin/node","gid":1001,"memoryUsage":{"arrayBuffers":40466,"external":1795043,"heapTotal":60968960,"heapUsed":58908256,"rss":103030784},"pid":1,"uid":1001,"version":"v14.19.0"},"stack":"AccessDenied: Access to the resource https://sqs.eu-west-1.amazonaws.com/ is denied.\n    at deserializeAws_queryCreateQueueCommandError (/webapp/main.js:554829:43)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async /webapp/main.js:550162:22\n    at async /webapp/main.js:563132:22\n    at async StandardRetryStrategy.retry (/webapp/main.js:560695:42)\n    at async /webapp/main.js:559369:24","timestamp":"2022-07-04T09:54:08.223Z","trace":[{"column":43,"file":"/webapp/main.js","function":"deserializeAws_queryCreateQueueCommandError","line":554829,"method":null,"native":false},{"column":5,"file":"internal/process/task_queues.js","function":"processTicksAndRejections","line":95,"method":null,"native":false},{"column":22,"file":"async /webapp/main.js","function":null,"line":550162,"method":null,"native":false},{"column":22,"file":"async /webapp/main.js","function":null,"line":563132,"method":null,"native":false},{"column":42,"file":"/webapp/main.js","function":"async StandardRetryStrategy.retry","line":560695,"method":"retry","native":false},{"column":24,"file":"async /webapp/main.js","function":null,"line":559369,"method":null,"native":false}]}`

I think this is on the code side. It's trying to create a queue as a backup of something else failing and it doesn't have access to create a queue

**Comment by pshomov** [comment]
Make sure there is a service-account associated with the service in the DSL
