### ISSUE TITLE
Create reusable field wrapper components for react-hook-form

### ISSUE THREAD

**Issue by darrikonn** [island-is/island.is#782]
Basically what is inside `libs/application/form/src/components/fields/**/*` could be made more generic and moved to `island-ui/core`.

Currently `island-ui/core` only has wrappers around `Formik` components, which are named `Field*`.
But we've come to a decision to replace `Formik` for `react-hook-form`. Therefore we'll need to create similar wrapper components for that as well. Might name them `*Controller`, e.g. `InputController`.

The deadline for that is as soon as possible to avoid other developers from choosing Formik for new projects. Currently, only `gjafakort` uses Formik -> and that project will be removed in the beginning of next year.

**Comment by ArniFreyrSnorrason** [comment]
I'm wondering if I should deprecate the formik fields in the process?

**Comment by darrikonn** [comment]
Yeah :+1:, just with a `NODE_ENV.development` warning for now. Can't be fully deprecated until the end of this year (when gjafakort will be deleted)

**Comment by ArniFreyrSnorrason** [comment]
https://github.com/island-is/island.is/pull/822

**Comment by ArniFreyrSnorrason** [comment]
Merged
