### ISSUE TITLE
Multiple language-togglers present

### ISSUE THREAD

**Issue by kristofer-lp8f** [island-is/island.is#7857]
When loading the front page of web (https://island.is), there are 3 language toggle buttons, but only 1 visible.

- More bytes/cpu/network is being used on something not visible/redundant
- I get code-smell seeing this, there must be more performance improvements possible

The front page is the second-most used page of all island.is pages ([plausible source](https://plausible.io/island.is/pages)) at 144K visits past 30 days.

_Originally posted by @kristofer-lp8f in https://github.com/island-is/island.is/issues/7711#issuecomment-1162915317_

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
