### ISSUE TITLE
Service-portal/inbox is made of divs

### ISSUE THREAD

**Issue by kristofer-lp8f** [island-is/island.is#7874]
The list of messages on a users inbox page is not a list in HTML. Instead the list is made up of nested `<div>` elements.

This decreases a11y.

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
