### ISSUE TITLE
Bug: ADS site links to prod

### ISSUE THREAD

**Issue by kristofer-lp8f** [island-is/island.is#7906]
1. Go to https://loftbru.dev01.devland.is/
2. Click "Sækja kóða"
3. Get redirected to https://loftbru.island.is/min-rettindi

Step 3 should redirect to https://loftbru.dev01.devland.is/min-rettindi

**Comment by busla** [comment]
Shouldnt step 3 redirect to https://loftbru.beta.dev01.devland.is/min-rettindi ?

**Comment by busla** [comment]
Since I cant have Cypress navigate too loftbru I have to create a messy workaround

**Comment by busla** [comment]
Looks like this bug is also affecting skilavottord

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
