### ISSUE TITLE
Bug: ADS logged in page flickers when not logged in

### ISSUE THREAD

**Issue by busla** [island-is/island.is#7911]
Reproduce
1. Go to https://island.is/loftbru
2. Click "Sækja kóða"
3. The logged in page `/min-rettindi` flickers for a second before redirecting to IDS

What should happen:
The `/min-rettindi` page should not be part of the request/response cycle until the user is logged in.

Related #7906, related #7882

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
