### ISSUE TITLE
Rotate secrets after github leak

### ISSUE THREAD

**Issue by peturgq** [island-is/island.is#7967]
Leaked secrets:
NOVA_PASSWORD
DOKOBIT_ACCESS_TOKEN
CONTENTFUL_ACCESS_TOKEN
CONTENTFUL_MANAGEMENT_ACCESS_TOKEN
XROAD_CLIENT_CERT
XROAD_CLIENT_KEY
XROAD_CLIENT_PEM

Slack:
https://islandis.slack.com/archives/C019LNRM6LE/p1656675487021389

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.
