### ISSUE TITLE
Add option to do feature deployments on IDS(Manual)

### ISSUE THREAD

**Issue by Snojo** [island-is/island.is#7976]

**Comment by Snojo** [comment]
We need to try to do a feature deploy on this https://github.com/island-is/island.is/pull/7189

**Comment by saevarma** [comment]
Tested the IDS Admin and auth services locally, and we are doing admin merge today.
But for the future it would be really nice to solve the automatic feature deployment of IDS services.

**Comment by peturgq** [comment]
Manual deployments should be possible, the process is just like the regular one but with some extra steps:

To test your feature for the auth api as an example you need to:
Create the namespace in k8s manually:
`kubectl create ns myfeature`

Generate the chart for the feature
`ts-node infra/src/feature-env.ts values --feature=myfeature --chart=identity-server --images=services-auth-api > myfeature.yaml`

Install the chart: 
global.image.tag would be the Island-is image tag you want to use
`helm upgrade -i -n feature-myfeature web . --values myfeature.yaml --set global.image.tag=39819_main_aaa056d --set identity-server.image.tag=887_tmp-audkenni-test2_3ef20f8`

Now you should have your features deployed in kube
