### ISSUE TITLE
Broken link in child-residence-change application email

### ISSUE THREAD

**Issue by rafnarnason** [island-is/island.is#8110]
https://github.com/island-is/island.is/blob/70f19b64f928de671fb158b016de8c92b00aef31/libs/application/template-api-modules/src/lib/modules/templates/children-residence-change/emailGenerators/applicationRejected.ts#L23

  const newApplicationLink = &#39;https://island.is/umsoknir/breytt-logheimili-barn&#39; is a 404

=> https://island.is/umsoknir/breytt-logheimili-barns is a 200 OK

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
