### ISSUE TITLE
Images containing a link should be described

### ISSUE THREAD

**Issue by kristofer-lp8f** [island-is/island.is#8148]
See [beta ADS](https://loftbru.dev01.devland.is/min-rettindi), Loftbrú Icon in right-hand-side side bar.
The SVG has no `description` element, while the other link-images (e.g. Vegagerðin) have a `description` element in their SVG.

This means screen readers can&#39;t say what the logo contains.

This is an issue for most icons/images.

Some fixes:
- ADS issue fixed by https://github.com/island-is/island.is/pull/8107

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
