### ISSUE TITLE
Wrong issuer in skilavottord causes failed e2e tests

### ISSUE THREAD

**Issue by busla** [island-is/island.is#8183]
When running system-e2e on skilavottord we depend on correct origins. Tests on dev therefore fail since the app uses ids-staging for federation.

```
Cross-Origin Read Blocking (CORB)
```
https://www.chromium.org/Home/chromium-security/corb-for-developers/

https://github.com/island-is/island.is/blob/main/apps/skilavottord/ws/src/environments/environment.ts#L7

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
