### ISSUE TITLE
Validate cy.session

### ISSUE THREAD

**Issue by kristofer-lp8f** [island-is/island.is#8226]
The session used by Cypress is cached, but there is currently no check for whether the session is still valid. The session could have expired, or the user is logged out.

If the session is invalid all `cy.visit(...)` statements requiring IDS login will redirect to IDS instead of the intended page.

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
