### ISSUE TITLE
Add validation of service name match between infra DSL and NX workspace

### ISSUE THREAD

**Issue by pshomov** [island-is/island.is#8483]
Aiming to avoid failures as the one introduced by this change - https://github.com/island-is/island.is/pull/8405/files#diff-a3c51ff0a2cbd98f60155ae63895530942ae68feedb0873d82e9bbfac489d01d

The service was renamed in NX but was never renamed in the infra DSL and thus failed at deployment time.

**Comment by eirikurn** [comment]
What about the ECR change?

Can we validate/automate that? Or do we document somewhere what developers need to do to deploy a new or renamed service?

**Comment by brynjarorng** [comment]
Get feedback from @pshomov on sanitation meeting

**Comment by peturgq** [comment]
Add build step that checks if DSL name matches with NX workspace name

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
