### ISSUE TITLE
Stop using any in createResolvers.ts

### ISSUE THREAD

**Issue by peturgq** [island-is/island.is#8705]
https://github.com/island-is/island.is/pull/8397#discussion_r981836084

This upgrade required us to break some type safety, we&#39;ll need to clean up after ourselves.

The [PR](https://github.com/island-is/island.is/pull/8397) in question is getting outdated and we need to merge sooner rather than later so new code that is introduced is compliant with the new version of typescript.

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
