### ISSUE TITLE
Build optimizations - part 2

### ISSUE THREAD

**Issue by pshomov** [island-is/island.is#8832]
- [x] #8975
- [x] Remove unused packages
- [ ] Persist cache in source(Maybe) - This is too heavy on git for little gain because we are still using the node_linker, would be too IO heavy
- [ ] Use workspaces and split up package.json and node_modules
      __See if depcheck can help us here, start with an empty package.json in a project and run depcheck to see what packages are missing.__
- [ ] Optimize build process to run each service in parallel - Would likely result in more GHA rate-limiting, but we can try.
- [ ] Look into distributed caching in NX
- [ ] Look into NX package.json generation

**Comment by JohannesOlafur** [comment]
this is waiting due to other priorities

**Comment by JohannesOlafur** [comment]
@peturgq add PR

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
