### ISSUE TITLE
Clients need clarification

### ISSUE THREAD

**Issue by kristofer-lp8f** [island-is/island.is#8885]
The library clients https://github.com/island-is/island.is/tree/main/libs/clients need clarification. In its `README` there is nothing.

I would like for there to be an explanation on what clients do and how they differ from the main API app and domains.

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
