### ISSUE TITLE
Persecutie bot to harass GH users that merge broken things to dev

### ISSUE THREAD

**Issue by peturgq** [island-is/island.is#8908]
We&#39;ve had a couple of times now that something is broken over extended periods on dev. 

Example of fallacies in current process and justification for spending some hours on making Persecutie.
(this is a near real world example):
1. Someone makes a change and applies automerge label
2. A week passes
3. Change is reviewed and automerged
4. Change is broken on dev(spinnaker fails to stabilize, crash loops on pods)
5. Week passes without anyone thinking specifically about succeeding dev pipeline in spinnaker
6. Someone makes changes to their app, app doesn&#39;t work because it uses the broken service above
7. Developer spends hours debugging his app before requesting help from devops
8. Batman goes on the hunt, spends an hour looking at logs, gathering info and looking at PR from 6.
9. Batman decides to check spinnaker and sees last two deployments on dev fail because manifests don&#39;t stabilize.
10. Batman sees that a pod is crashlooping on dev cluster
11. Batman checks log for that pod - See&#39;s the pod has been having the same issue for a week.
12. a) Batman finally checks spinnaker and with luck doesn&#39;t crash when showing 30 runs of the deployment pipeline.
      b) Batman goes through noisy history in #deployments
13. Batman finds the offending git hash that first broke dev
14. Batman goes into deep recon on offending PR, calls in devs responsible if needed.
15. Batman finally finds the issue, devs make a fix, all is good again... Until next time.
16. Batman asks how this happened, was the feature not tested on dev?
17. Dev /shrugs because he/she made this two weeks ago, release train cycle will test these changes.

Just from this we can make assumptions on just how much time was wasted because a developer wasn&#39;t harassed about the broken change that was deployed that he/she hasn&#39;t been thinking about for two weeks.

We could make a slack bot that "persecutes" devs that break this, so that they&#39;ll know immediately if their change broke something on dev when their change is merged.

We need to figure out a way to translate github user with slack user without dealing with the overhead of maintaining that mapping somehow.

Find associated PR that is causing failed spinnaker deployment and extract the user responsible for the merge.

Send a warning to user on slack

Considerations when making this:
- Not spammy
  - We don&#39;t care about successes
  - Only ping when there is an issue
  - Ping only with concise helpful information for dev to make the mental connection
- Make it clear to the dev that he/she is responsible to make the deployment green again if their change caused this.
- If the dev pipeline is broken for _n_ time(dev ignores persecution) then escalate to a more public channel
  - Extra motivation because of shame factor 😛 

Nice to haves:
- Deployment system agnostic
- Direct message to user on slack
- Send info on which deployment is failing to stabilize
  - Send links to a datadog search tuned to the failing deployment.

**Comment by peturgq** [comment]
Will bump this up a bit because we are currently taking the heat for broken code on dev.

Possibly might have a fancy solution on mapping GH users to slack users without much overhead:
1. Post to channel with link to offending commit and GH user name
2. Bot checks if this user is mapped, doesn't find it.
3. Someone replies to slack thread and @'s person manually
4. Bot picks up the @'ed user and maps it in parameter store/s3/dynamo
5. Harasses

Next time
1. ...
2. Checks and finds mapped user
3. Harasses

I want this to help create a "you break it you fix it" mentality,
where the only person who fixes main is the author of the culprit commit because sometimes being the good samaritan is more harmful and solidifies bad patterns in development.

This would promote healthier accountability and ownership views and hopefully less friction.

**Comment by brynjarorng** [comment]
Too complicated, look for alternative implementations that achieve a similar result

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
