### ISSUE TITLE
Remove prometheus client if not used

### ISSUE THREAD

**Issue by brynjarorng** [island-is/island.is#8913]
`prom-client` is creating quite a few deprecation warnings but it is possibly not used. Look at either upgrading or removing it.

(PR to upgrade)[https://github.com/island-is/island.is/pull/8911]

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
