### ISSUE TITLE
Invalid entry in list of Icelandic names (mannanafnaskrá)

### ISSUE THREAD

**Issue by alexharri** [island-is/island.is#9010]
In [IcelandicName.csv](https://github.com/island-is/island.is/blob/e19b56f4d34ad20e0337ae73140a1c71afb9356c/apps/icelandic-names-registry/backend/data/IcelandicName.csv#L4560) the entry on line 4560 with the ID 4638 seems to be invalid.

The name reads `Da,` (including the comma) and this is the only entry with an `Afgreitt` value of `NULL`. It also doesn&#39;t include a `Tegund` value.

It shows up on https://island.is/leit-i-mannanafnaskra:

<img width="644" alt="image" src="https://user-images.githubusercontent.com/20321920/201513060-8715fc14-39e0-4ceb-86cc-01452255d18f.png">

I&#39;m not sure where the data for `IcelandicName.csv` originates from (the PR that added it does not clarify). Perhaps this entry is also malformed at the source?

**Comment by kksteini** [comment]
I think @stjanilofts set this up. Maybe he knows how to move forward with this.

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
