### ISSUE TITLE
Fix postinstall after yarn berry upgrade

### ISSUE THREAD

**Issue by peturgq** [island-is/island.is#9029]
Seems postinstall is not working after the berry upgrade, running `yarn` simply doesn&#39;t run the postinstall

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
