### ISSUE TITLE
Fix missing global env variables

### ISSUE THREAD

**Issue by pshomov** [island-is/island.is#9169]
That&#39;s weird. Let&#39;s fix that issue after this fix.

_Originally posted by @pshomov in https://github.com/island-is/island.is/pull/9133#discussion_r1033415737_

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
