### ISSUE TITLE
DSL notes in gitbook

### ISSUE THREAD

**Issue by pshomov** [island-is/island.is#9221]
I would prefer getting this in GitBook and replace code references with proper markdown documentation/examples.

_Originally posted by @eirikurn in https://github.com/island-is/island.is/pull/8862#discussion_r1031720217_

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
