### ISSUE TITLE
Error message in driving licence needs better accessibility

### ISSUE THREAD

**Issue by kristofer-lp8f** [island-is/island.is#9386]
Working on `/umsoknir/okuskoli`, getting an error message on step 3 ("Staðfesta ökuskóla").

The error message has a `paragraph` role, and the icon next to it is a `diagram`. They are not grouped into a "error" container, and I see no ARIA alert property.

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
