### ISSUE TITLE
Duplicate button

### ISSUE THREAD

**Issue by kristofer-lp8f** [island-is/island.is#9391]
In `/umsoknir/okuskoli`, when picking a date, the selector `[data-testid="step-back"]` has two elements. I.e. there are actually two back buttons, both visible according to the browser, but only one is visible to the eye.

There should only be one button.

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
