### ISSUE TITLE
Look into feature deployment dependencies and nx affected components

### ISSUE THREAD

**Issue by peturgq** [island-is/island.is#9456]
Possible feature deployment improvements
- [ ] Infra changes don&#39;t seem to be detected as true changes to components, this seems to be because `**/infra/*` is in .nxignore
      Do we really want this? This would pretty much couple infra with app, which seems like a really bad idea. lets try to find a different solution
- [x] #9478
- [x] #9480
    `/feature-add-service "$APP"` would deploy $APP with the feature deployment

**Comment by peturgq** [comment]
https://github.com/island-is/island.is/pull/9455

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
