### ISSUE TITLE
Fix dependency issue, web and api are not being deployed when the only way to truly test some components is through web or api - Extend the new work around upstream/downstream dependencies with some kind of logic for components relying on web/api.

### ISSUE THREAD

**Issue by pshomov** [island-is/island.is#9478]

**Comment by brynjarorng** [comment]
Add documentation regarding how we can use refs in the DSL config to "force" deploy dependant apps

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
