### ISSUE TITLE
Set better convention/lint for national IDs in code

### ISSUE THREAD

**Issue by kristofer-lp8f** [island-is/island.is#9502]
The first prefix may match a real person and these do not match some of the newer fake ids which we might need to use in some tests. 

I don&#39;t mind this change at all, but I also don&#39;t mind using eslint-ignore. Additionally, we could have something like this:

```
import { FakePerson } from &#39;@island.is/testing/fixtures&#39;

// enum access:
FakePerson.gervimadurUtlond // 0101307789
```

Also, these fake ids should only be used in system-e2e tests. I think all other tests should use `createNationalId()`.

_Originally posted by @eirikurn in https://github.com/island-is/island.is/pull/9477#discussion_r1060771732_

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
