### ISSUE TITLE
System-e2e cognito session check needs improvement

### ISSUE THREAD

**Issue by kristofer-lp8f** [island-is/island.is#9522]
When deploying to staging I see several failures, all of which are timeouts when `get`ting `https://beta.staging01.devland.is/`.

This network error rate can be severely reduced if we share a common Cognito session.

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
