### ISSUE TITLE
Stop running ALL tests when new commit is added to PR

### ISSUE THREAD

**Issue by peturgq** [island-is/island.is#9857]
Scenario:
Change code in 5 applications

All these 5 applications are built and tested.
Now I make another commit which only changes code in 1 of these 5 apps

Entire build/test suite for those 5 applications is triggered 👎 

Lets change this and only build on deltas between most recent commit and last commit when working with PR&#39;s somehow - This will take some planning and diving into stickman

Maybe distributed nx caching will also save us here.

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
