### ISSUE TITLE
Fix missing login.js

### ISSUE THREAD

**Issue by pshomov** [island-is/island.is#986]
It affects seems gjafakort, vidspyrna and loftbrú. For example for Loftbrú when you press “Sjá réttindi” tries to load file login.js which is missing. This is causing problems in monitoring.

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
