### ISSUE TITLE
Add query parameter to disable existing application screen in application system

### ISSUE THREAD

**Issue by kristofer-lp8f** [island-is/island.is#9950]
Please add a query parameter to disable existing application screen in application system. When testing applications, the existing applications screen adds unnecessary complexity; it&#39;s currently dealt with using imperfect GraphQL mocks. This native support would also be nice for manual testing.

TL;DR
- Add `showExistingApplications=(true|false)` query parameter in application system

**Comment by andes-it** [comment]
This issue's been twiddling its thumbs for 5 days. Daydreaming, perhaps? Best do something or it's curtains in 1 day. Nudge off the stale label to give it another go.

**Comment by andes-it** [comment]
This issue's shut up shop. Gave it a day post-stale, then decided, "Enough's enough!"
